/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

export {
  AddressSpace,
  BaseResource,
  CloudError,
  ErrorDetails,
  ErrorModel,
  ListP2SVpnGatewaysResult,
  P2SVpnGateway,
  P2SVpnProfileParameters,
  Resource,
  SubResource,
  TagsObject,
  VpnClientConnectionHealth,
  VpnProfileResponse
} from "../models/mappers";
