/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

export {
  AddressSpace,
  BaseResource,
  BgpPeerStatus,
  BgpPeerStatusListResult,
  BgpSettings,
  CloudError,
  GatewayRoute,
  GatewayRouteListResult,
  IpsecPolicy,
  Resource,
  SubResource,
  TagsObject,
  TunnelConnectionHealth,
  VirtualNetworkConnectionGatewayReference,
  VirtualNetworkGateway,
  VirtualNetworkGatewayConnectionListEntity,
  VirtualNetworkGatewayIPConfiguration,
  VirtualNetworkGatewayListConnectionsResult,
  VirtualNetworkGatewayListResult,
  VirtualNetworkGatewaySku,
  VpnClientConfiguration,
  VpnClientIPsecParameters,
  VpnClientParameters,
  VpnClientRevokedCertificate,
  VpnClientRootCertificate,
  VpnDeviceScriptParameters
} from "../models/mappers";
