trigger:
  - master

variables:
  node.version: '10.x'

jobs:
  - job: 'Publish'

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '$(node.version)'
        displayName: 'Install Node.js $(node.version)'

      # Rather than running "npm install" in the repo root, reduce build time by only installing the "npm-run-all" package,
      # which is the minimum required to run the composite script commands.
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'install npm-run-all'
        displayName: 'npm install npm-run-all'

      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run install-client'
        displayName: 'npm run install-client'

      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run build-client'
        displayName: 'npm run build-client'

      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run pack-client'
        displayName: 'npm run pack-client'

      - task: CopyFiles@2
        inputs:
          contents: 'packages/**/*.tgz'
          targetFolder: $(Build.ArtifactStagingDirectory)
          flattenFolders: true
        displayName: 'Copy Packages'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Package'

 

 
 


